"""Chinese-first progressive presentation assets for the read-only Workstream graph."""

WORKSTREAM_GRAPH_CSS = r"""
body:has(#workstream-relation-graph.on) .toc{display:none}body:has(#workstream-relation-graph.on) main.content{min-width:0}#workstream-relation-graph.page.wide.on{width:100%;max-width:none}
.wg-shell{--wg-cyan:#6ee7dd;--wg-yellow:#f4c96b;--wg-red:#ff786c;--wg-ink:#dce6f2;--wg-dim:#94a3b7;--wg-node-width:248px;--wg-node-height:104px;position:relative;width:100%;margin:0 0 24px;border:1px solid var(--line);border-radius:15px;overflow:hidden;background:linear-gradient(180deg,rgba(110,231,221,.045),transparent 230px),var(--bg)}
.wg-shell *{box-sizing:border-box}.wg-mast{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;padding:22px 24px 17px;border-bottom:1px solid var(--line)}.wg-kicker,.wg-panel-index{margin:0;color:var(--wg-cyan);font:700 10px/1.3 "Cascadia Code",Consolas,monospace;letter-spacing:.12em}.wg-mast h2{margin:4px 0;font-size:26px;letter-spacing:-.025em}.wg-mast p{max-width:760px;margin:0;color:var(--mut);font-size:12.5px}.wg-seal{align-self:start;padding:7px 10px;border:1px solid var(--line);border-radius:6px;color:var(--wg-dim);font:700 10px/1.2 "Cascadia Code",Consolas,monospace}.wg-seal.ready::before{content:"◇ ";color:var(--wg-cyan)}.wg-seal.unavailable::before{content:"? ";color:var(--wg-yellow)}
.wg-failure{margin:16px 24px 0;padding:12px 14px;border:1px dashed var(--wg-yellow);background:rgba(244,201,107,.06);color:var(--mut);border-radius:8px}.wg-failure b{display:block;color:var(--wg-yellow);margin-bottom:3px}.wg-controls{padding:16px 24px;border-bottom:1px solid var(--line)}.wg-lenses{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:var(--line);border:1px solid var(--line);border-radius:9px;overflow:hidden}.wg-lens{min-width:0;border:0;border-radius:0;padding:11px 13px;background:var(--bg2);color:var(--fg);font:inherit;text-align:left;cursor:pointer}.wg-lens span{display:block;color:var(--mut);font:700 9px/1.2 "Cascadia Code",Consolas,monospace}.wg-lens b{display:block;margin-top:3px}.wg-lens[aria-pressed="true"]{box-shadow:inset 0 -3px 0 var(--wg-cyan);background:rgba(110,231,221,.08)}
.wg-filterbar{display:grid;grid-template-columns:minmax(145px,1fr) minmax(145px,1fr) repeat(3,auto);gap:8px;margin-top:10px}.wg-filterbar label{display:grid;gap:4px;color:var(--mut);font-size:10px}.wg-filterbar select,.wg-button{min-height:38px;border:1px solid var(--line);border-radius:7px;background:var(--bg2);color:var(--fg);font:600 11px/1.2 inherit;padding:0 10px}.wg-button{align-self:end;cursor:pointer;white-space:nowrap}.wg-button:hover{border-color:var(--wg-cyan)}.wg-viewbar{display:flex;align-items:center;gap:7px;margin-top:9px;flex-wrap:wrap}.wg-viewbar .wg-button{min-width:38px}.wg-viewbar-note{margin-right:auto;color:var(--mut);font-size:10.5px}.wg-zoom-readout{min-width:46px;text-align:center;color:var(--wg-dim);font:700 10px/1.2 "Cascadia Code",Consolas,monospace}
.wg-grid{min-height:560px}.wg-graph-panel{min-width:0;width:100%;padding:18px 20px 20px}.wg-panel-head{display:flex;justify-content:space-between;gap:14px;align-items:end}.wg-panel-head h3{margin:3px 0 0;font-size:17px}.wg-legend{display:flex;gap:12px;flex-wrap:wrap;color:var(--mut);font-size:10px}.wg-legend i{display:inline-block;width:24px;border-top:3px solid var(--wg-cyan);vertical-align:middle;margin-right:5px}.wg-legend .dependency{border-top-style:dashed;border-color:var(--wg-yellow)}.wg-legend .conflict{border-top-style:double;border-top-width:5px;border-color:var(--wg-red)}
.wg-frame{position:relative;margin-top:12px;height:480px;border:1px solid var(--line);border-radius:9px;overflow:hidden;background:var(--bg2)}.wg-viewport{width:100%;height:100%;overflow:auto;overscroll-behavior:contain;cursor:grab;background-image:linear-gradient(rgba(148,163,183,.065) 1px,transparent 1px),linear-gradient(90deg,rgba(148,163,183,.065) 1px,transparent 1px);background-size:28px 28px}.wg-viewport.is-panning{cursor:grabbing;user-select:none}.wg-canvas{position:relative;min-width:100%;min-height:100%;padding:0}.wg-frame svg{display:block;max-width:none;overflow:visible}.wg-lane{fill:rgba(148,163,183,.035);stroke:rgba(148,163,183,.16);stroke-width:1}.wg-lane-title{fill:var(--wg-dim);font:700 11px "Cascadia Code",Consolas,monospace;letter-spacing:.06em}.wg-lane-index{fill:var(--wg-cyan);font:700 9px "Cascadia Code",Consolas,monospace}
.wg-edge{fill:none;stroke-width:3;stroke-linejoin:round;stroke-linecap:square;vector-effect:non-scaling-stroke}.wg-edge.lens-succession{stroke:var(--wg-cyan)}.wg-edge.lens-dependency{stroke:var(--wg-yellow);stroke-dasharray:12 8}.wg-edge.lens-conflict{stroke:var(--wg-red);stroke-width:4;stroke-dasharray:18 5 3 5}.wg-edge.proposed{opacity:.72}.wg-edge.stale{opacity:.56}.wg-edge.uncertain{opacity:.72}.wg-edge-hit{fill:none;stroke:transparent;stroke-width:20;pointer-events:stroke;cursor:pointer;outline:none}.wg-edge-hit:focus,.wg-edge-hit:focus-visible{outline:none}.wg-edge-hit:focus-visible{stroke:var(--wg-ink);stroke-width:11;stroke-dasharray:2 7;opacity:.45;vector-effect:non-scaling-stroke}
.wg-node{cursor:pointer}.wg-node>rect{fill:var(--bg);stroke:var(--line);stroke-width:2}.wg-node.current>rect{stroke:var(--wg-cyan);stroke-width:3}.wg-node.direct>rect{stroke:#aebbd0}.wg-node.history>rect{stroke:var(--wg-dim);stroke-dasharray:5 4}.wg-node.unknown>rect{stroke:var(--wg-yellow);stroke-dasharray:7 5}.wg-node.conflict>rect{stroke:var(--wg-red);stroke-width:3}.wg-node.cluster>rect{fill:rgba(110,231,221,.045);stroke:var(--wg-dim);stroke-dasharray:8 5}.wg-node.cluster:hover>rect{stroke:var(--wg-cyan)}.wg-node-role{font:700 10px "Cascadia Code",Consolas,monospace}.wg-node.current .wg-node-role{fill:var(--wg-cyan)}.wg-node.direct .wg-node-role,.wg-node.history .wg-node-role,.wg-node.cluster .wg-node-role{fill:var(--wg-dim)}.wg-node.unknown .wg-node-role{fill:var(--wg-yellow)}.wg-node.conflict .wg-node-role{fill:var(--wg-red)}.wg-node-prefix{fill:var(--fg);font:800 15px "Cascadia Code",Consolas,monospace}.wg-node-name{fill:var(--wg-ink);font:700 13px/1.2 "Microsoft YaHei UI","PingFang SC",sans-serif}.wg-node-id{fill:var(--wg-dim);font:10px "Cascadia Code",Consolas,monospace}.wg-node-meta{fill:var(--wg-dim);font:10px "Microsoft YaHei UI","PingFang SC",sans-serif}.wg-chain-collapse rect{fill:var(--bg2);stroke:var(--wg-cyan);stroke-width:1}.wg-chain-collapse text{fill:var(--wg-cyan);font:700 9px "Microsoft YaHei UI","PingFang SC",sans-serif}.wg-chain-collapse:focus-visible{outline:none}.wg-chain-collapse:focus-visible rect{stroke:var(--wg-yellow);stroke-width:3}.wg-empty{position:absolute;inset:0;display:grid;place-content:center;padding:36px;text-align:center;color:var(--mut);background:var(--bg2);pointer-events:none}.wg-empty b{color:var(--fg);font-size:18px}.wg-empty p{max-width:520px;margin:9px auto 0;font-size:12px;line-height:1.65}.wg-empty small{display:block;margin-top:10px;color:var(--wg-dim);font:700 10px/1.4 "Cascadia Code",Consolas,monospace}.wg-empty[hidden]{display:none}
.wg-inspector[hidden]{display:none!important}.wg-inspector{position:absolute;z-index:20;top:12px;right:12px;bottom:12px;width:min(390px,calc(100% - 24px));overflow:auto;padding:18px;border:1px solid var(--line);border-radius:10px;background:var(--bg);box-shadow:-10px 0 35px rgba(0,0,0,.32)}.wg-inspector-head{display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid var(--line);padding-bottom:10px;color:var(--mut);font:700 9px/1.2 "Cascadia Code",Consolas,monospace;letter-spacing:.08em}.wg-inspector-close{width:34px;height:34px;border:1px solid var(--line);border-radius:7px;background:var(--bg2);color:var(--fg);font-size:20px;cursor:pointer}.wg-inspector h3{margin:15px 0 4px;font-size:18px;overflow-wrap:anywhere}.wg-inspector-summary{margin:0 0 12px;color:var(--mut);font-size:12px}.wg-axis{display:grid;grid-template-columns:minmax(90px,.75fr) minmax(0,1.25fr);gap:8px;padding:7px 0;border-top:1px solid var(--line);font-size:11px}.wg-axis span{color:var(--mut)}.wg-axis b{overflow-wrap:anywhere;text-align:right}.wg-reasons{margin:8px 0;padding-left:17px;color:var(--wg-yellow);font:10px/1.6 "Cascadia Code",Consolas,monospace}.wg-evidence{display:grid;gap:6px;margin-top:12px}.wg-evidence a,.wg-evidence span{display:block;max-width:100%;padding:7px 8px;border:1px solid var(--line);border-radius:6px;color:var(--mut);font:10px/1.35 "Cascadia Code",Consolas,monospace;overflow-wrap:anywhere}.wg-evidence a{color:var(--wg-cyan);text-decoration:none}.wg-readonly{margin-top:14px;padding-top:10px;border-top:1px solid var(--line);color:var(--mut);font-size:10px}
.wg-ledger{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border:0}.wg-ledger h3{margin:0 0 4px}.wg-ledger-intro{margin:0 0 12px;color:var(--mut);font-size:11px}.wg-ledger-rank{margin:12px 0 7px;color:var(--wg-cyan);font:700 10px "Cascadia Code",Consolas,monospace}.wg-ledger-list{display:grid;gap:8px}.wg-ledger-item{width:calc(100% - var(--wg-indent,0px));margin-left:var(--wg-indent,0px);min-width:0;padding:11px;border:1px solid var(--line);border-left:4px solid var(--wg-cyan);border-radius:7px;background:var(--bg2);color:var(--fg);font:inherit;text-align:left}.wg-ledger-item.direct{border-left-color:#aebbd0}.wg-ledger-item.history,.wg-ledger-item.cluster{border-left-color:var(--wg-dim);border-left-style:dashed}.wg-ledger-item.unknown{border-left-color:var(--wg-yellow);border-left-style:dashed}.wg-ledger-item.conflict{border-left-color:var(--wg-red)}.wg-ledger-item b,.wg-ledger-item small{display:block;overflow-wrap:anywhere}.wg-ledger-item small{margin-top:4px;color:var(--mut)}.wg-ledger-collapse{width:auto;margin-left:auto;padding:7px 10px;border:1px solid var(--wg-cyan);border-radius:6px;background:var(--bg2);color:var(--wg-cyan);font:700 10px inherit}.wg-ledger-edge{padding:9px 11px;border:1px solid var(--line);border-radius:7px;background:rgba(148,163,183,.035);color:var(--fg);text-align:left}.wg-ledger-edge b{color:var(--wg-cyan)}.wg-ledger-edge.dependency b{color:var(--wg-yellow)}.wg-ledger-edge.conflict b{color:var(--wg-red)}.wg-ledger-edge small{display:block;margin-top:4px;color:var(--mut);overflow-wrap:anywhere}.wg-ledger-empty{padding:14px;border:1px dashed var(--line);color:var(--mut)}
.wg-lens:focus-visible,.wg-button:focus-visible,.wg-filterbar select:focus-visible,.wg-ledger-item:focus-visible,.wg-ledger-edge:focus-visible,.wg-node:focus-visible,.wg-inspector-close:focus-visible,.wg-evidence a:focus-visible{outline:3px solid var(--wg-yellow);outline-offset:3px}.wg-node:focus-visible{outline:none}.wg-node:focus-visible>rect{stroke:var(--wg-yellow);stroke-width:4}.wg-sr{position:absolute!important;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
@media(max-width:900px){.wg-filterbar{grid-template-columns:repeat(2,minmax(0,1fr)) repeat(3,auto)}.wg-frame{height:430px}}
@media(max-width:640px){header.top{gap:8px;padding:0 12px}.top h1{min-width:0;overflow:hidden;text-overflow:ellipsis}.top .sub,.searchwrap{display:none}.rightgrp{min-width:0;gap:6px}.wg-mast{grid-template-columns:1fr;padding:18px}.wg-seal{justify-self:start}.wg-controls{padding:14px 18px}.wg-lenses{grid-template-columns:1fr}.wg-filterbar{grid-template-columns:minmax(0,1fr)}.wg-filterbar label,.wg-filterbar select,.wg-button{min-width:0;width:100%}.wg-viewbar{display:none}.wg-grid{min-height:0}.wg-graph-panel{display:none}.wg-ledger{position:static;width:auto;height:auto;padding:16px 18px;margin:0;overflow:visible;clip-path:none;white-space:normal;border-top:1px solid var(--line)}.wg-inspector{position:fixed;top:auto;left:8px;right:8px;bottom:8px;width:auto;max-height:78vh;border-radius:12px}.wg-shell{max-width:100%;overflow:hidden}}
@media(prefers-reduced-motion:reduce){.wg-shell *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
"""


WORKSTREAM_GRAPH_JS = r"""
(()=>{'use strict';
const page=document.querySelector('#workstream-relation-graph');if(!page)return;
const data=JSON.parse(page.querySelector('[data-wg-payload]').textContent);
const svg=page.querySelector('[data-wg-svg]'),viewport=page.querySelector('[data-wg-viewport]'),ledger=page.querySelector('[data-wg-ledger]');
const inspector=page.querySelector('[data-wg-inspector-shell]'),inspectorBody=page.querySelector('[data-wg-inspector]'),live=page.querySelector('[data-wg-live]');
const subsystem=page.querySelector('[data-wg-subsystem]'),runtime=page.querySelector('[data-wg-runtime]'),zoomReadout=page.querySelector('[data-wg-zoom-readout]');
const state={lens:'succession',expandedChains:new Set(),subsystem:'all',runtime:'all',selection:null,zoom:1};
const NS='http://www.w3.org/2000/svg',NODE_W=248,NODE_H=104,RANK_GAP=112,ROW_GAP=34,MIN_ZOOM=.55,MAX_ZOOM=1.6;
const nodeMap=new Map((data.nodes||[]).map(n=>[n.workstream_id,n]));
const activeTipIds=new Set(data.active_tip_workstream_ids||[]);
const phaseLabels={created:'已创建',planning:'规划中',implementing:'实现中',validating:'验证中','review-ready':'等待审查',integrated:'已集成',closed:'已关闭',historical:'历史记录',unknown:'待确认'};
const runtimeLabels={active:'进行中',paused:'已暂停','waiting-for-user':'等待确认','blocked-by-conflict':'存在冲突',failed:'失败',offline:'离线',collapsed:'已收起',unknown:'待确认'};
const evidenceLabels={current:'当前',stale:'历史状态',unknown:'待确认',historical:'历史记录'};
const subsystemLabels={'authority-meta-model':'权威模型','documentation-system':'文档系统','multi-worktree-collaboration':'多工作树协作','project-structure':'项目结构','release-and-toolchain':'发布与工具链','test-coverage':'测试覆盖',unknown:'模块待确认','历史任务':'历史任务'};
const shown=(map,value)=>map[value]||value||'待确认';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const se=(tag,attrs={})=>{const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));return n};
const sorted=value=>[...value].sort((a,b)=>String(a).localeCompare(String(b)));
function keyboardActivate(target,action){target.addEventListener('click',action);target.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();action()}})}
function relationLabel(edge){if(state.lens==='conflict')return edge.certainty==='confirmed'?'已确认冲突':'需要比较';if(edge.collapsedHistoryEdge)return'历史接续';if(edge.lifecycle==='proposed'||edge.certainty==='unknown')return state.lens==='dependency'?'依赖待确认':'接续待确认';if(edge.lifecycle==='stale')return state.lens==='dependency'?'历史依赖':'历史接续';return state.lens==='dependency'?'依赖':'接续'}
function rawLensEdges(){
  if(state.lens==='conflict')return(data.conflicts||[]).map((edge,index)=>{const pair=[edge.source_workstream_id,edge.target_workstream_id].sort();return{...edge,displayFrom:pair[0],displayTo:pair[1],displayEdgeId:edge.id||`conflict-${index}`}});
  const allowed=state.lens==='succession'?new Set(['derived_from','absorbs']):new Set(['depends_on']);
  return(data.edges||[]).filter(edge=>allowed.has(edge.relation_type)&&edge.lifecycle!=='cancelled').map((edge,index)=>({...edge,displayFrom:edge.target_workstream_id,displayTo:edge.source_workstream_id,displayEdgeId:edge.relation_id||`edge-${index}`}));
}
function matches(node){return(state.subsystem==='all'||node.primary_subsystem_id===state.subsystem||(node.affected_subsystem_ids||[]).includes(state.subsystem))&&(state.runtime==='all'||node.runtime_condition===state.runtime)}
function orderedAncestors(tip,incoming){const found=new Set(),ordered=[];function visit(id){sorted(incoming.get(id)||[]).forEach(item=>{if(found.has(item))return;found.add(item);visit(item);ordered.push(item)})}visit(tip);return ordered}
function buildModel(){
  let edges=rawLensEdges();const allowedNodes=new Set((data.nodes||[]).filter(matches).map(node=>node.workstream_id));
  edges=edges.filter(edge=>allowedNodes.has(edge.displayFrom)&&allowedNodes.has(edge.displayTo));
  const endpointIds=new Set();edges.forEach(edge=>{endpointIds.add(edge.displayFrom);endpointIds.add(edge.displayTo)});if(state.lens==='succession')activeTipIds.forEach(id=>{if(allowedNodes.has(id))endpointIds.add(id)});
  const incoming=new Map(),outgoing=new Map();endpointIds.forEach(id=>{incoming.set(id,new Set());outgoing.set(id,new Set())});
  edges.forEach(edge=>{outgoing.get(edge.displayFrom).add(edge.displayTo);incoming.get(edge.displayTo).add(edge.displayFrom)});
  const visibleFactIds=new Set(),chains=[],claimedHistory=new Set();
  if(state.lens==='conflict'){endpointIds.forEach(id=>visibleFactIds.add(id))}else{
    const lensTips=state.lens==='succession'?[...activeTipIds].filter(id=>endpointIds.has(id)):[];
    const tips=sorted(new Set([...endpointIds].filter(id=>!(outgoing.get(id)||new Set()).size).concat(lensTips)));
    tips.forEach(tip=>{const chainId=`chain:${tip}`,direct=new Set(incoming.get(tip)||[]),siblings=new Set();direct.forEach(id=>(outgoing.get(id)||[]).forEach(value=>siblings.add(value)));const defaults=new Set([tip,...direct,...siblings]);const older=orderedAncestors(tip,incoming).filter(id=>!defaults.has(id)&&!claimedHistory.has(id));older.forEach(id=>claimedHistory.add(id));defaults.forEach(id=>visibleFactIds.add(id));if(state.expandedChains.has(chainId))older.forEach(id=>visibleFactIds.add(id));chains.push({chainId,tipId:tip,directIds:sorted(direct),historyIds:older,expanded:state.expandedChains.has(chainId)})});
  }
  const nodes=sorted(visibleFactIds).map(id=>{const item=nodeMap.get(id);return item?{...item}:null}).filter(Boolean),hiddenOwner=new Map();
  chains.forEach(chain=>{if(!chain.expanded||!chain.historyIds.length)return;const toggleNode=nodes.find(node=>node.workstream_id===chain.historyIds[0]);if(toggleNode){toggleNode.collapse_chain_id=chain.chainId;toggleNode.expanded_history_count=chain.historyIds.length}});
  chains.forEach(chain=>{if(chain.expanded||!chain.historyIds.length)return;const clusterId=`history:${chain.tipId}`;chain.historyIds.forEach(id=>hiddenOwner.set(id,clusterId));nodes.push({workstream_id:clusterId,display_prefix:`+${chain.historyIds.length}`,display_name:'折叠的上游链',status:'inactive',runtime_condition:'collapsed',lifecycle_phase:'historical',evidence_freshness:'historical',scope_status:'historical',primary_subsystem_id:'历史任务',source_links:[],is_cluster:true,chain_id:chain.chainId,cluster_ids:chain.historyIds,cluster_first_id:chain.historyIds[0],cluster_last_id:chain.historyIds[chain.historyIds.length-1],cluster_tip_id:chain.tipId})});
  const nodeIds=new Set(nodes.map(node=>node.workstream_id)),displayEdges=[],seen=new Set();
  edges.forEach(edge=>{const from=hiddenOwner.get(edge.displayFrom)||edge.displayFrom,to=hiddenOwner.get(edge.displayTo)||edge.displayTo;if(from===to||!nodeIds.has(from)||!nodeIds.has(to))return;const key=`${from}>${to}:${edge.relation_type}`;if(seen.has(key))return;seen.add(key);displayEdges.push({...edge,displayFrom:from,displayTo:to,collapsedHistoryEdge:from!==edge.displayFrom||to!==edge.displayTo})});
  const indegree=new Map([...nodeIds].map(id=>[id,0])),adjacency=new Map([...nodeIds].map(id=>[id,new Set()]));displayEdges.forEach(edge=>{if(!adjacency.get(edge.displayFrom).has(edge.displayTo)){adjacency.get(edge.displayFrom).add(edge.displayTo);indegree.set(edge.displayTo,indegree.get(edge.displayTo)+1)}});
  const rank=new Map([...nodeIds].map(id=>[id,0])),queue=sorted([...nodeIds].filter(id=>indegree.get(id)===0)),visited=new Set();while(queue.length){const id=queue.shift();visited.add(id);sorted(adjacency.get(id)).forEach(to=>{rank.set(to,Math.max(rank.get(to),rank.get(id)+1));indegree.set(to,indegree.get(to)-1);if(indegree.get(to)===0){queue.push(to);queue.sort()}})}sorted([...nodeIds].filter(id=>!visited.has(id))).forEach(id=>rank.set(id,state.lens==='conflict'?1:0));
  const groups=new Map();nodes.forEach(node=>{const value=rank.get(node.workstream_id)||0;if(!groups.has(value))groups.set(value,[]);groups.get(value).push(node)});groups.forEach(values=>values.sort((a,b)=>(Boolean(b.is_cluster)-Boolean(a.is_cluster))||a.workstream_id.localeCompare(b.workstream_id)));
  const undirected=new Map([...nodeIds].map(id=>[id,new Set()]));displayEdges.forEach(edge=>{undirected.get(edge.displayFrom).add(edge.displayTo);undirected.get(edge.displayTo).add(edge.displayFrom)});const components=[],assigned=new Set();sorted(nodeIds).forEach(seed=>{if(assigned.has(seed))return;const members=[],pending=[seed];assigned.add(seed);while(pending.length){const id=pending.shift();members.push(id);sorted(undirected.get(id)).forEach(next=>{if(!assigned.has(next)){assigned.add(next);pending.push(next)}})}components.push(sorted(members))});
  const nodeTop=112,positions=new Map();let rowCursor=0;components.sort((a,b)=>a[0].localeCompare(b[0])).forEach((members,componentIndex)=>{const memberSet=new Set(members),byRank=new Map();sorted(groups.keys()).forEach(rankValue=>{const values=(groups.get(rankValue)||[]).filter(node=>memberSet.has(node.workstream_id));if(values.length)byRank.set(rankValue,values)});const componentRows=Math.max(1,...[...byRank.values()].map(values=>values.length));byRank.forEach((values,rankValue)=>values.forEach((node,localRow)=>positions.set(node.workstream_id,{x:36+rankValue*(NODE_W+RANK_GAP),y:nodeTop+(rowCursor+localRow)*(NODE_H+ROW_GAP),w:NODE_W,h:NODE_H,rank:rankValue,row:rowCursor+localRow,component:componentIndex})));rowCursor+=componentRows+1});const maxRows=Math.max(1,rowCursor?rowCursor-1:1);
  const routes=displayEdges.map((edge,index)=>{const from=positions.get(edge.displayFrom),to=positions.get(edge.displayTo),sx=from.x+from.w,sy=from.y+from.h/2,tx=to.x,ty=to.y+to.h/2,rankSpan=Math.max(1,to.rank-from.rank),mid=Math.round((sx+tx)/2);let points;if(sy===ty&&rankSpan===1)points=[[sx,sy],[tx,ty]];else if(rankSpan===1)points=[[sx,sy],[mid,sy],[mid,ty],[tx,ty]];else{const startChannel=sx+22,endChannel=tx-22,trackY=Math.max(88,Math.min(from.y,to.y)-20-(index%4)*8);points=[[sx,sy],[startChannel,sy],[startChannel,trackY],[endChannel,trackY],[endChannel,ty],[tx,ty]]}return{edge,points,lineEncoding:state.lens==='dependency'?'dashed':state.lens==='conflict'?'compound':'solid'}});
  const maxRank=nodeIds.size?Math.max(...groups.keys()):-1,lanes=[];for(let value=0;value<=maxRank;value++){const values=groups.get(value)||[];let title=values.some(node=>node.is_cluster)?'更早历史':values.some(node=>activeTipIds.has(node.workstream_id))?'当前任务':value===maxRank?'当前／后续任务':'直接前置／依赖';lanes.push({rank:value,title})}
  const roles=new Map();nodes.forEach(node=>{let role='history';if(node.is_cluster)role='cluster';else if(state.lens==='conflict')role='conflict';else if([node.status,node.runtime_condition,node.evidence_freshness,node.scope_status].includes('unknown'))role='unknown';else if(activeTipIds.has(node.workstream_id)||chains.some(chain=>chain.tipId===node.workstream_id))role='current';else if(chains.some(chain=>chain.directIds.includes(node.workstream_id)))role='direct';roles.set(node.workstream_id,role)});
  return{nodes,edges:displayEdges,chains,positions,routes,lanes,roles,width:nodeIds.size?72+(maxRank+1)*NODE_W+maxRank*RANK_GAP:1,height:nodeIds.size?nodeTop+maxRows*(NODE_H+ROW_GAP)+34:1,visibleFactIds:sorted(visibleFactIds)};
}
function pathData(points){let path=`M${points[0][0]} ${points[0][1]}`;for(let index=1;index<points.length;index++){const previous=points[index-1],point=points[index];path+=point[1]===previous[1]?` H${point[0]}`:` V${point[1]}`}return path}
function shortId(value,max=29){return value.length>max?value.slice(0,max-1)+'…':value}
function nameLines(value){const chars=[...String(value||'任务记录')];return[chars.slice(0,15).join(''),chars.slice(15,30).join('')].filter(Boolean)}
function roleCopy(role){return{current:'● 当前任务',direct:'◆ 直接前置',history:'◷ 历史任务',unknown:'? 待确认',conflict:'! 冲突／比较',cluster:'▸ 展开上游链'}[role]||'任务'}
function markerId(){return state.lens==='dependency'?'wg-arrow-dependency':state.lens==='conflict'?'wg-arrow-conflict':'wg-arrow-succession'}
function openInspector(kind,item){state.selection={kind,item};renderInspector();inspector.hidden=false;inspector.setAttribute('aria-hidden','false');live.textContent=(kind==='node'?'已选择任务 ':'已选择关系 ')+(item.workstream_id||item.relation_id||item.id)}
function closeInspector(){inspector.hidden=true;inspector.setAttribute('aria-hidden','true');state.selection=null;live.textContent=''}
function renderInspector(){inspectorBody.replaceChildren();if(!state.selection)return;const {kind,item}=state.selection,heading=el('h3',null,kind==='node'?(item.display_prefix||'任务')+' · '+(item.display_name||'任务记录'):relationLabel(item));const summary=el('p','wg-inspector-summary',kind==='node'?'完整机器标识与证据轴':'记录方向与屏幕阅读方向分开显示');inspectorBody.append(heading,summary);const axes=kind==='node'?[['完整任务 ID',item.workstream_id],['生命周期',item.lifecycle_phase],['运行状态',item.runtime_condition],['证据状态',item.evidence_freshness],['范围状态',item.scope_status],['项目模块',item.primary_subsystem_id],['可见范围',item.visibility],['观测来源',item.observability]]:[['关系类型',item.relation_type],['生命周期',item.lifecycle],['确定性',item.certainty],['屏幕方向',item.displayFrom+' → '+item.displayTo],['Core source',item.source_workstream_id],['Core target',item.target_workstream_id],['处置',item.disposition||'edge']];axes.forEach(([key,value])=>{const row=el('div','wg-axis');row.append(el('span',null,key),el('b',null,value==null?'Unknown':String(value)));inspectorBody.append(row)});const reasons=item.reason_codes||item.evidence_reason_codes||[];if(reasons.length){const list=el('ul','wg-reasons');reasons.forEach(reason=>list.append(el('li',null,reason)));inspectorBody.append(list)}const links=el('div','wg-evidence');(item.source_links||[]).forEach(link=>{const node=link.href?el('a',null,link.kind+' · '+link.ref):el('span',null,link.kind+' · '+link.ref);if(link.href){node.href=link.href;node.rel='noopener'}links.append(node)});if(!(item.source_links||[]).length)links.append(el('span',null,'没有可跳转的来源链接；证据状态见上方技术字段。'));inspectorBody.append(links)}
function toggleChain(chainId){state.expandedChains.has(chainId)?state.expandedChains.delete(chainId):state.expandedChains.add(chainId);render()}
function humanLabel(id){const item=nodeMap.get(id);return item?`${item.display_prefix||'任务'} · ${item.display_name||'任务记录'}`:String(id)}
function renderNode(node,position,role){const clusterSummary=node.is_cluster?`${node.cluster_ids.length} 个连续前序任务，${humanLabel(node.cluster_first_id)} 到 ${humanLabel(node.cluster_last_id)}`:'';const group=se('g',{class:`wg-node ${role}`,tabindex:0,role:'button','aria-label':node.is_cluster?`${roleCopy(role)}，${clusterSummary}`:`${roleCopy(role)} ${node.display_prefix||''} ${node.display_name||''}`});group.append(se('rect',{x:position.x,y:position.y,width:position.w,height:position.h,rx:9}));const title=se('title');title.textContent=node.is_cluster?`${clusterSummary}：${node.cluster_ids.join('、')}`:node.workstream_id;group.append(title);const roleText=se('text',{x:position.x+14,y:position.y+20,class:'wg-node-role'});roleText.textContent=roleCopy(role);const prefix=se('text',{x:position.x+14,y:position.y+42,class:'wg-node-prefix'});prefix.textContent=node.display_prefix||'任务';group.append(roleText,prefix);nameLines(node.display_name).forEach((line,index)=>{const text=se('text',{x:position.x+64,y:position.y+42+index*17,class:'wg-node-name'});text.textContent=line;group.append(text)});const machine=se('text',{x:position.x+14,y:position.y+79,class:'wg-node-id'});machine.textContent=node.is_cluster?shortId(`${humanLabel(node.cluster_first_id)} → ${humanLabel(node.cluster_last_id)}`,36):shortId(node.workstream_id);const meta=se('text',{x:position.x+14,y:position.y+96,class:'wg-node-meta'});meta.textContent=node.is_cluster?'点击展开，仅影响这条上游链':`${shown(subsystemLabels,node.primary_subsystem_id)} · ${shown(runtimeLabels,node.runtime_condition)}`;group.append(machine,meta);if(node.collapse_chain_id){const control=se('g',{class:'wg-chain-collapse',tabindex:0,role:'button','aria-label':`收起本链，${node.expanded_history_count} 个上游任务`}),controlRect=se('rect',{x:position.x+position.w-82,y:position.y+8,width:70,height:23,rx:5}),controlText=se('text',{x:position.x+position.w-47,y:position.y+23,'text-anchor':'middle'});controlText.textContent='收起本链';const collapse=event=>{event.preventDefault();event.stopPropagation();toggleChain(node.collapse_chain_id)};control.addEventListener('click',collapse);control.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')collapse(event)});control.append(controlRect,controlText);group.append(control)}const action=node.is_cluster?()=>toggleChain(node.chain_id):()=>openInspector('node',node);keyboardActivate(group,action);return group}
function emptyMessage(){if(data.status!=='ready')return'当前没有完整证据，因此未生成不完整关系图。';if(state.lens==='dependency')return'当前没有已登记的依赖关系';if(state.lens==='conflict')return'当前没有已登记的冲突关系';return'当前没有已登记的接续关系'}
function renderEmpty(empty,model){empty.replaceChildren();if(model.nodes.length){empty.hidden=true;return}const title=el('b',null,emptyMessage()),detail=el('p',null,data.status!=='ready'?'只有完整、只读且哈希绑定的证据才能进入关系图。':state.lens==='dependency'?'接续关系不等于依赖关系。本页不会把接续边重复画成依赖，也不会用没有连线的任务填满画布。':state.lens==='conflict'?'只有已登记的冲突对会出现在这里；没有证据时不推断冲突。':'当前筛选条件没有留下可显示的接续链。'),count=el('small',null,state.lens==='dependency'?'0 条依赖边 · 0 个孤立节点':state.lens==='conflict'?'0 组冲突对':'0 条可见接续边');empty.append(title,detail,count);empty.hidden=false}
function renderLedger(model){ledger.replaceChildren();ledger.dataset.factIds=model.visibleFactIds.join('|');if(!model.nodes.length&&!model.edges.length){ledger.append(el('div','wg-ledger-empty',emptyMessage()));return}const labels=new Map(model.nodes.map(node=>[node.workstream_id,node.is_cluster?node.display_name:`${node.display_prefix||'任务'} · ${node.display_name||'任务记录'}`]));model.lanes.forEach(lane=>{ledger.append(el('div','wg-ledger-rank',`第 ${lane.rank+1} 层 · ${lane.title}`));model.nodes.filter(node=>model.positions.get(node.workstream_id).rank===lane.rank).forEach(node=>{const role=model.roles.get(node.workstream_id),button=el('button',`wg-ledger-item ${role}`);button.type='button';button.style.setProperty('--wg-indent',`${Math.min(lane.rank,3)*12}px`);button.append(el('b',null,`${roleCopy(role)} · ${node.display_prefix||'任务'} · ${node.display_name||'任务记录'}`),el('small',null,node.is_cluster?`${node.cluster_ids.length} 项已折叠；点击只展开这一条链。`:shortId(node.workstream_id,44)));keyboardActivate(button,node.is_cluster?()=>toggleChain(node.chain_id):()=>openInspector('node',node));ledger.append(button);if(node.collapse_chain_id){const collapse=el('button','wg-ledger-collapse',`收起本链 · ${node.expanded_history_count} 项`);collapse.type='button';keyboardActivate(collapse,()=>toggleChain(node.collapse_chain_id));ledger.append(collapse)}});model.edges.filter(edge=>model.positions.get(edge.displayTo).rank===lane.rank).forEach(edge=>{const button=el('button',`wg-ledger-edge ${state.lens}`);button.type='button';button.title=`${edge.displayFrom} → ${edge.displayTo}`;button.append(el('b',null,relationLabel(edge)),el('small',null,`从 ${labels.get(edge.displayFrom)||'待确认任务'} → 到 ${labels.get(edge.displayTo)||'待确认任务'}`));keyboardActivate(button,()=>openInspector('edge',edge));ledger.append(button)})})}
function render(){const model=buildModel();svg.replaceChildren();svg.dataset.factIds=model.visibleFactIds.join('|');svg.setAttribute('viewBox',`0 0 ${model.width} ${model.height}`);svg.setAttribute('width',String(model.width*state.zoom));svg.setAttribute('height',String(model.height*state.zoom));zoomReadout.textContent=`${Math.round(state.zoom*100)}%`;const defs=se('defs');[['succession','#6ee7dd'],['dependency','#f4c96b'],['conflict','#ff786c']].forEach(([id,color])=>{const marker=se('marker',{id:`wg-arrow-${id}`,viewBox:'0 0 12 12',refX:10.5,refY:6,markerWidth:10,markerHeight:10,markerUnits:'userSpaceOnUse',orient:'auto'});marker.append(se('path',{d:'M2 2L10.5 6L2 10Z',fill:color}));defs.append(marker)});svg.append(defs);model.lanes.forEach(lane=>{const x=20+lane.rank*(NODE_W+RANK_GAP),rect=se('rect',{x,y:36,width:NODE_W+32,height:model.height-54,rx:10,class:'wg-lane'}),index=se('text',{x:x+16,y:56,class:'wg-lane-index'}),title=se('text',{x:x+16,y:74,class:'wg-lane-title'});index.textContent=`层级 ${String(lane.rank+1).padStart(2,'0')}`;title.textContent=lane.title;svg.append(rect,index,title)});model.routes.forEach(route=>{const edge=route.edge,label=relationLabel(edge),lifecycle=edge.lifecycle==='proposed'?'proposed':edge.lifecycle==='stale'?'stale':'confirmed',group=se('g'),path=se('path',{d:pathData(route.points),class:`wg-edge lens-${state.lens} ${lifecycle} ${edge.certainty==='confirmed'?'':'uncertain'}`,'marker-end':`url(#${markerId()})`}),hit=se('path',{d:pathData(route.points),class:'wg-edge-hit',tabindex:0,role:'button','aria-label':`${label}，从 ${edge.displayFrom} 到 ${edge.displayTo}`});keyboardActivate(hit,()=>openInspector('edge',edge));group.append(path,hit);svg.append(group)});model.nodes.forEach(node=>svg.append(renderNode(node,model.positions.get(node.workstream_id),model.roles.get(node.workstream_id))));renderLedger(model);renderEmpty(page.querySelector('[data-wg-empty]'),model);page.querySelector('[data-wg-expand-all]').disabled=!model.chains.some(chain=>chain.historyIds.length);page.querySelector('[data-wg-collapse-all]').disabled=!state.expandedChains.size;window.__orreryWorkstreamGraph={model,state};}
function zoomAt(value,anchorX,anchorY){const previous=state.zoom,next=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,value));if(Math.abs(next-previous)<.001)return;const worldX=(viewport.scrollLeft+anchorX)/previous,worldY=(viewport.scrollTop+anchorY)/previous;state.zoom=next;render();viewport.scrollLeft=worldX*next-anchorX;viewport.scrollTop=worldY*next-anchorY;live.textContent=`关系图缩放到 ${Math.round(next*100)}%`}
function setZoom(value){zoomAt(value,viewport.clientWidth/2,viewport.clientHeight/2)}
function fit(){const model=buildModel();if(!model.nodes.length){state.zoom=1;render();return}const width=Math.max(1,viewport.clientWidth-24),height=Math.max(1,viewport.clientHeight-24);state.zoom=Math.max(1,Math.min(1.15,width/model.width,height/model.height));render();viewport.scrollTo({left:0,top:0,behavior:'smooth'});live.textContent=state.zoom===1?'已定位全图起点；为保持可读，未缩小到 100% 以下。':`关系图缩放到 ${Math.round(state.zoom*100)}%`}
function reset(){state.lens='succession';state.expandedChains.clear();state.subsystem='all';state.runtime='all';state.zoom=1;subsystem.value='all';runtime.value='all';page.querySelectorAll('[data-wg-lens]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.wgLens==='succession')));closeInspector();render();viewport.scrollTo({left:0,top:0})}
function options(select,values,labels={}){sorted(new Set(values.filter(Boolean))).forEach(value=>{const option=el('option',null,labels[value]||value);option.value=value;select.append(option)})}
options(subsystem,(data.nodes||[]).flatMap(node=>[node.primary_subsystem_id,...(node.affected_subsystem_ids||[])]),subsystemLabels);options(runtime,(data.nodes||[]).map(node=>node.runtime_condition),runtimeLabels);
page.querySelectorAll('[data-wg-lens]').forEach(button=>button.addEventListener('click',()=>{state.lens=button.dataset.wgLens;page.querySelectorAll('[data-wg-lens]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));closeInspector();render()}));
subsystem.addEventListener('change',()=>{state.subsystem=subsystem.value;render()});runtime.addEventListener('change',()=>{state.runtime=runtime.value;render()});
page.querySelector('[data-wg-expand-all]').addEventListener('click',()=>{buildModel().chains.filter(chain=>chain.historyIds.length).forEach(chain=>state.expandedChains.add(chain.chainId));render()});page.querySelector('[data-wg-collapse-all]').addEventListener('click',()=>{state.expandedChains.clear();render()});page.querySelector('[data-wg-zoom-in]').addEventListener('click',()=>setZoom(state.zoom+.1));page.querySelector('[data-wg-zoom-out]').addEventListener('click',()=>setZoom(state.zoom-.1));page.querySelector('[data-wg-fit]').addEventListener('click',fit);page.querySelector('[data-wg-reset]').addEventListener('click',reset);page.querySelector('[data-wg-inspector-close]').addEventListener('click',closeInspector);
viewport.addEventListener('wheel',event=>{if(!event.ctrlKey)return;event.preventDefault();const rect=viewport.getBoundingClientRect(),anchorX=event.clientX-rect.left,anchorY=event.clientY-rect.top,factor=event.deltaY<0?1.1:.9;zoomAt(state.zoom*factor,anchorX,anchorY)},{passive:false});
let pan=null;viewport.addEventListener('pointerdown',event=>{if(event.target.closest('.wg-node,.wg-edge-hit'))return;pan={x:event.clientX,y:event.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};viewport.classList.add('is-panning');viewport.setPointerCapture(event.pointerId)});viewport.addEventListener('pointermove',event=>{if(!pan)return;viewport.scrollLeft=pan.left-(event.clientX-pan.x);viewport.scrollTop=pan.top-(event.clientY-pan.y)});function endPan(){pan=null;viewport.classList.remove('is-panning')}viewport.addEventListener('pointerup',endPan);viewport.addEventListener('pointercancel',endPan);page.addEventListener('keydown',event=>{if(event.key==='Escape'&&!inspector.hidden)closeInspector()});
render();closeInspector();
})();
"""


__all__ = ["WORKSTREAM_GRAPH_CSS", "WORKSTREAM_GRAPH_JS"]
